apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseer
  namespace: media
  labels:
    dep: jellyseer-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseer
  template:
    metadata:
      labels:
        app: jellyseer
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: jellyseer
          
          image: fallenbagel/jellyseerr:develop
          resources:
            requests: 
              memory: 500m
              cpu: 500m
            limits:
              memory: 4Gi
             
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: config
              mountPath: /app/config

      volumes:
        - name: config
          persistentVolumeClaim:
             claimName: jellyseer-config
