apiVersion: v1
kind: Service
metadata:
  name: jellyseer-service
  
  namespace: media
  labels:
    app: jellyseer_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 5055
    protocol: TCP
    targetPort: 5055
    
  selector:    
    app: jellyseer
  type: LoadBalancer
  loadBalancerIP: 10.0.40.163