apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token
  namespace: network
spec:
  encryptedData:
    token: AgCZBPciAKQOUhluX/V9x1uaa3rlf/f4LmsT7UyQ0p3Y3J3wq86aIl+dcdxrAfHCD1KvThfzQnY/vYeTsYaw6PIRrFGkolTPFoxD/cFujbVKAWs4k+ySvUE7IeBOBGOssQM2Y+sllfo/ZLGlpjcSfn7mQcM31y9tVZCo7qVybWXCmhYc3F5qXgM0/aK8W2i9jPHzKMDzHXBkSyiqmF94qQLnd0yGPiyISDCTrsauBsid+J2eWxPEyoBTfmKmz2averLo6iVuf+0+sRRbcrT3X+mvSwsWtIm5yYddsOAmYwOWzapQxikV2Nng4aaWuodCUP4UqJiipXWyKe+dXsHXqglZGYmkV1gHzNtFN7RIL4d4O/r+kmpKKspXrwhhAElnkWH0Xe/dnEkMHYYPbsDzwJPyELwgq3sJ/RM06IIJNOee2SFGPSeNIrFl7h+pw2LAA2Yq5Ot1Erx3nTKJMfB0oqa3Dj48LK+x6IpFpP5jqelElKoFhjBGH5FlbFLmNFlCK4kXtEr25clzKaJ9L+bqErNsOBaXZJ4zkT1TkDdVNCqWD54vnDSKIXoq4kHQVkpgabMZAmnASiX6RfGU2EOdLaY5lwc3k56U/8gnLaWeAEGzTk+hHNFKvpjEyRMoxUAryMIQ+kvdRnqrHSlyqk3jOpkY5x17jG/HbduqLfJL/EPhS8eAtA1PhdPZocwYILRPOJhJZJLiFkQZ2gGmqC8xFAOg7fgM8MLZKSr3EqKd6Pk7J/FZLc2kD3bpg9z6Gk5fFOV9PDtE9eVzsq2yMyK+uOZlEBqyPc0kA6/+sgUEZ4jTRFWf5RFOoNV05XbgoRZ0cDKVt18NrgdI9g0px5HsgpRr6cxZC/VBljOR9jjHmB05ATwguxKhlGEBfupltnnuu3Sko4CCzi7XeGqayec9rmU0dUoqH1rGHjRg2KEgUhnKn6fyL3HAW2Jq
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token
      namespace: network
    type: Opaque

