apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replication
spec:
  selector:
    matchLabels:
      app: mysql-replication
  serviceName: mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql-replication
    spec:
      initContainers:
      - name: create-database
        image: mysql:8.0
        command:
        - sh
        - -c
        - |
          set -e
          echo "CREATE DATABASE ignition_db;" | mysql --user=root --password=password --host=mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_REPLICATION_USER
          value: replication_user
        - name: MYSQL_REPLICATION_PASSWORD
          value: replication_password
        - name: MYSQL_REPLICATION_MODE
          value: "true"
        - name: MYSQL_REPLICATION_MASTER_HOST
          value: mysql-replication-0.mysql
        - name: MYSQL_REPLICATION_MASTER_PORT
          value: "3306"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
