apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-set
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb"
  replicas: 2
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: scadadb-data
          mountPath: /var/lib/mysql
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mariadb-password
                key: MARIADB_ROOT_PASSWORD
      volumeClaimTemplates:
       - metadata:
         name: scadadb-data
         spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi