apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-replication
spec:
  ports:
  - port: 3306
    name: mysql-port
  clusterIP: None
  selector:
    app: mysql-replication