apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
    app: mariadb

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb-read
  labels:
    app: mariadb
    app.kubernetes.io/name: mariadb
    readonly: "true"
spec:
  ports:
  - name: mariadb
    port: 3306
  selector:
    app: mariadb