apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels:
    dep: jellyfin-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: jellyfin
          
          image: ghcr.io/linuxserver/jellyfin:latest
          resources:
            requests: 
              memory: 500m
              cpu: 500m
            limits:
              memory: 4Gi
              
          ports:
          - name: port8096
            containerPort: 8096
          - name: port8920
            containerPort: 8920
          - name: port7359
            containerPort: 7359
          - name: port1900
            containerPort: 1900

          volumeMounts:
            - name: media
              mountPath: /media

            - name: config
              mountPath: /config

      volumes:
        - name: media
          nfs:
            server: 10.0.50.4
            path: /mnt/Slow/Media

        - name: config
          persistentVolumeClaim:
             claimName: jellyfin-config
