apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  
  namespace: media
  labels:
    app: jellyfin_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8096
  - name: http2
    port: 8920
    protocol: TCP
    targetPort: 8920 
  - name: http3
    port: 7359
    protocol: UDP
    targetPort: 7359
  - name: http4
    port: 1900
    protocol: UDP
    targetPort: 1900
    
  selector:    
    app: jellyfin
  type: LoadBalancer
  loadBalancerIP: 10.0.40.164