apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: network
  labels:
    dep: pihole-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
     
      
    spec:
      containers:
        - name: pihole
          image: pihole/pihole
          resources:
            requests: 
              memory: 500m
              cpu: 500m
            limits:
              memory: 4Gi
             
          ports:
            - containerPort: 80
            - containerPort: 53
            - containerPort: 443
            - containerPort: 67
          volumeMounts:
            - name: config
              mountPath: /etc/pihole

           

            

      volumes:  
        - name: config
          persistentVolumeClaim:
             claimName: pihole-config
