apiVersion: v1
kind: Service
metadata:
  labels:
    app: pihole
  name: pihole-tcp
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: dns
    protocol: TCP
    port: 53
    targetPort: dns
  - name: pihole-http
    port: 80
    protocol: TCP
    targetPort: pihole-http
  selector:
    app: pihole
  sessionAffinity: None
  type: LoadBalancer
