apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
