apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfinaccount
  namespace: media
  labels:
    dep: jellyfin-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfinaccount
  template:
    metadata:
      labels:
        app: jellyfinaccount
     
      
    spec:
      containers:
        - name: jellyfinaccount
          
          image: hrfee/jfa-go
          resources:
            requests: 
              memory: 2Gi
              cpu: 1000m
            limits:
              memory: 4Gi
              cpu: 2000m
          ports:
            - containerPort: 8056
          volumeMounts:
            - name: config
              mountPath: /data

       volumes:             
       - name: config
         persistentVolumeClaim:
             claimName: jellyfinaccount-config
