apiVersion: v1
kind: Service
metadata:
  name: jellyfinaccount-service
  
  namespace: media
  labels:
    app: jellyfinaccount-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8056
    
  selector:    
    app: jellyfinaccount
  type: LoadBalancer
  loadBalancerIP: 10.0.40.167