apiVersion: v1
kind: Service
metadata:
  name: homarr-service
  
  namespace: network
  labels:
    app: homarr_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7575
    
  selector:    
    app: homarr
  type: LoadBalancer
  loadBalancerIP: 10.0.40.168