apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-config
  namespace: network
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
