apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deluge-secret
  namespace: media
spec:
  encryptedData:
    VPN_PASS: AgBUS1k+djfcywJDo7BB/jUWNmIHAgBU904bcedHxDKS4HW+0VpnTziE2hNKiYko/OI9SdxYSQtsfRJGN+NqsXte8ZHdQeiodV7E5zorW/WhHghI97xOLOw5lgGTiXAqtrU+nKVMQLKkWekV6BIfyKJ0KnASX4GJFcc30bsbJ0zZlSI7WvYXItQeis8IzHOC5/5Zt3S8TvUF8waYvjxiqx+10lYVokFyWcDV4jN9zoL0U9FS8j737tBrNOKi9IVa98qrSI1248v3mHngDhxETludHdquLtnkz64WbV9YZI7PL4j5kognOEw7Dqjja+38gZ1A6rJZDr/od1hZAajWUsn8Q75QcOKvVAON7sdt1bWz5qXyJWcBo6mPSVcME1Xq/qThiN8fH5td09K04lO0Nbe1D85gRHRbbR4Kgr0f0q+Jlme6cJmnh3TlUAkhvKZKpXPZE27LexNE980UdwXFrmcEG0KJjjVFgYPrDEJh8AJXzasQZhpr3r8szq0fD4IM5UaQRR17XbnYri9mOXNHUb4fTKZkgVtqMP8zlMxzh2N9TecJgGqoXYbL5zAgTYVLFhq6JCZfOCajCzz8lSc+lJIWf/hR3rWp1Udj4OhR/VgNXz6ZWGis97m0aOaE0iDfecHl5C4pzIN4W+6cyby+YpwIjmjcGi1MITyG5I7/cEMWIDpU7PjJPeoUqMjkq6e4nCR/
    VPN_USER: AgCeWvTyE7rEjO5B+gqWjDE1bSgbfdAsHVAu21rb9FvQcv6UL8VCOcqKsODMGhhHJqZVb/j/gWOfI0qnxB0aVYp9GbkGDaJ02varLcK1TYu9K28GHpHe5FRubw2yNZVNq3atR3yVzRW+phzmv9wJslxEG06CQ16EiadkzeLL2fKMaMpHHmZHXuqDBqsP3vn55McPBsnl/Y8V2yGsxX9nxG91vz4rI7doUrDxZjdgXZtqN6R7FV2kLjJCKxJi5BZNLKsvN5wzS3alLiezVksS3blRYRTv1BXy2jZd4pMPiWqOsQaJ+Hyx/bW7IO/sQ8CjBMR04qVfNrpyuRVQpAveC3dJWZDcfQCHBcEGPCIFrH2jF6ZftkAsisPcNvC56+e4UG+Sq+8lHuOZpmk1ino+OB0HdNypkBIoUGktYDzgNcDy4IuA5QLwnK1QKzi1rkClwwqN1XD2EsAm2tqn8dRdA83ToNvh8LWl1kB0xYcOPKi5j16IB+KQ8UxHiFZH62ukQeYx1fT/h+0kimQ/YWmXGBKnVTI3PfkRwrHOz7fGzhjqGrhc1F3MU7UHMKNsk+AZTe/ZAFVH2+icgRHOG2S1ppZXuBmgG3ktS7ovHuLXxhdhEou9G5GGUSSO3HopZyiqKm9NXvi8aVYULbfIzLQc3x5HKngmcMnHiSpHYE+kng23m2A42DqRqST6wbYIsqo5vjqPBSU6VOv1kQuTMEmVtMNF
  template:
    metadata:
      creationTimestamp: null
      name: deluge-secret
      namespace: media
    type: Opaque

