apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deluge-secret
  namespace: media
spec:
  encryptedData:
    VPN_PASS: AgB5w74oUPSsR7WqDOoPaL+uLyTCUF/P/V2R1kN6z0tGflqvNDTTHdSh5qDD7zevuEtn7NJ3nzQ9ea31noE1HUMnnLAsYQDGwcKrqfSSF1ZQuvXtgrfg+6fH8v6Yq6JPdo/o5gXgeDBxJZEiygvYujGhely9f6dUl7upnVxbhx14teTpv2hQUcQW0vURVosruxocchLCaGq9ry41MumnDwCzyc1xujts+znUh2gYFPGvIP/bQgfKB9zm9K+Ks09pHPEAxNqA+O9dxS2iVrX/K48n4gVsMXvlBUBirfJwmkA4I7GSa7PAuf2duDt2457X7bpvyhibJa/Lra9qXXm/lJgX53fo9JvuXazP9M/B9eUH9go3smLc/NY2G+VCmZCzkgS07Ky7wGd8QMmLp8qo5vlwM6ko5abTi86RRJ8yZMOjD3L30QDOvC64euEzvC0sqG0dLSNthRyRlT1ZrZGZKu5DshdsI55xP3g/kVwDO5vvZT7A+rNVrQlxNW9+9HuOGhtz1l5g6JlGlZMsGWRefZsUaMBSsgyOAT8mTmZaG3jy8g6YnSwn8bPxuhiUAMzAJ4pVr4SLqcbsPQmhG9mfAyr6ojAiezi5JIeGoxAxBlQSiqK8qYcGzRJAomR9h4Cdu1+ybE0Y6COyfMj0j1PVMrmWvo8Matf2DwH7KGOUHOW9tkc86DOxRUBHdrKKCNlFkaAg
    VPN_USER: AgBgMO9x7Y8F/D/V05gaRd9hLUQEc6PbE9gGA5Wpb3X/v5qL7vDLCcJtm+AQST4Bz5Uj3uN4FuNM8DdmzwOc6mKgkUh9BjqYh6UdaTYjAgfNfd+7+VQXo3OjTfmQhg+VKLad/+Sk50+YeFwPVij1SZtVXPqVrx6Pkv+lt9HkB+amGAA0LltIO1AwTuobWC44WMnxbJPkE2EpHsdwiBZ8g0UPjCxhhgLicVbqBHw5SPLkRivl4ZY3ggEujDKH2RKMyk/6DOsTrxabPy3j5Hnw5FcjC0O8e0FKbute60g8P9Er77ic/baefgKP4TuDkiUDHKQY0fvxHoMqmfvQI/cu+xxyB4tmGLDeBP4jcsibDKr967XnqqbdjRC62Jnd9cSu5y8ovvyucni3G3LMhLAgJQ6W/y7t62evkAPmGSy19sMMX7+CwXfUqhS/E3CECJofMMsVtCYupYHPSuPptseKs3oMC/sx6072WEVvCj4hgMQxWTzePZHBpSNldHnb2cteEZwKZXv4mWSzltUpcT31DUiHtU7ImiuwcMdKCFL1qWjwmiYLkmtJ/GWNJuun66MBGyzwxaKWNXWwHpdLtG93vYSlW8HBTuA2N4QF8zDIGN7ZXPzfz31l9lPHCr4oB061KdWk/kLS+efaPsC8NRV/MjyHKhb8zttKTUZZVbqdariIjhEMcq+qUV4wqvjRTzfh65tDYv/CGYB6GVNrIGxlVSp2
  template:
    metadata:
      creationTimestamp: null
      name: deluge-secret
      namespace: media
    type: Opaque

