apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: deluge-secret
  namespace: media
spec:
  encryptedData:
    VPN_PASS: AgCKE6RAOcaSr82hLiK5LKNah+A6E5v43FpIoiar2pGlXULnFRJRbO7YlBnnH9z35oKRIeaVB7h1UHXAJRfsVms10c5IiCkx80B5/Zac+Q59zjbj7tKhbZeveKxnwFoHsoyTfhOJUENc+BhD6npxtPUWW8SbpS6WCMoVXErbCf6GVYatE1PagF0I88WIaoUYCduJNz1+shUhhskT8hAe9js1xZhUWIlQF9uCzTt3ntcD+pZingIWQfI5rDTXgU4fn55kYMUgEo9bs1LX2xrV9JtMnIrm4DIzi3CKHCSwJkab55ChJ984uUI5tHrM25PrOaNi2bKU7B6Z/5uWBx6E92nvkeZUHATBKXtSKW1fUDUFziQqpG1CsJzNXz9qkH6TwYzCSz6UPuYwMZiY4AmhP1clw4+NNryu3xvajscgc2vie2jUtepp+gWvBF/QcJj9Y7Fubj1iQ+dp3CK6SgnzZSSIto6oYTgCox9HejCnt8HC9KucLbWP+vmNXQPHKnvT3GptlLsLsBfN9YXlQCGNakth5KYeTd38fJsjF9uYtt5fohP18grtRDUrB8VdtRofE8ErdkEe3frMDbroMx8wrVJinF39c5lVQ8OWKlnVvABmSX+ZkBmbyq4KaxVUYGixdI/IwoM9h5zDTU6x+rpDeMpaGScACnXINfo7fnnh53yraO4LiDF5c9i1YHtj/FblPHgD
    VPN_USER: AgAS8MxjTxXrK03Tp0GUQ646L38ov1w0CWG8GNk2pqW7vZ02sc0Og21173LJxusql3J6ISZk0ALbaecFUpmV/U3AsYC8cNTFgrnH3LfOvXUf5jLkTkSWmyKO9luSetWuq2sgk6Rsp8+s4LaANJpAiYxnnvOjhTOq1a+CWqQ1qibHi/S2fkI5NLZAOfuPahjXCYSTSnPFfQIeEUQY/2VG6whuPxqbQBM6cghGy13ugt6IpOJhW6R7D48p0BbY+sJrlluTzc7IlQ1dajViD+ySzIFc9T75KISl3r0QW3G+rzcx1WLEw6k3P0UTAhJgu4SB1NlMmmzFRawr8ugDwH+faDqyjUMe63EctXV/XOBF8grxzlFP1YmfLAvuqbag6PGAsoBEa95bvGLxfvyKeJiUU8VbbFVllp1U6WkUsbnD8kV6wjd+rwe7sPcHFCNrYjLhEdqZSoiEDnoiSV3uY44Xvlxp+xtyQuNhwJ4L37EVNPIA6zy5sJYOJO28ymrCg7j0UWKD7lqsSETKkduiIM8/yCqr4RkPDGbZUnVg8LM81Sv9D+4PYfQDsjZ8aU2EKZJ1TtfLhQS5fhznhHuHZmSpbRqaOkGuqqwE1VuyTsu/Jh8Gfq1SFVLA0/UoT2efYcRFPlzpT42ErWdrMsJP0HCqEWBsg9uuAUJyjV/16GzKq5Fgfon/xPH8wj+xzw3GSBDYa38x2jKyljtD8ESNv6kBidVo
  template:
    metadata:
      creationTimestamp: null
      name: deluge-secret
      namespace: network
    type: Opaque

