apiVersion: apps/v1
kind: Deployment
metadata:
  name: scada-frontend
  namespace: scada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scada-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scada-frontend
    spec:
      initContainers:
      - name: seed-volume
        image: inductiveautomation/ignition:8.1.17
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        command:
        - sh
        - -c
        - >
          if [ ! -f /data/.ignition-seed-complete ]; then
            touch /data/.ignition-seed-complete ;
            cp -dpR /usr/local/bin/ignition/data/* /data/ ;
          fi
        volumeMounts:
        - mountPath: /data
          name: scadafrontend-data
      containers:
      - name: scada-frontend
        image: inductiveautomation/ignition:8.1.17
        resources:
          requests:
            memory: 200m
            cpu: 500m
          limits:
            memory: 2Gi


        env:
        - name: ACCEPT_IGNITION_EULA
          value: "Y"
        - name: TZ
          value: “America/Pacific”
        - name: IGNITION_EDITION
          value: standard
        - name: GATEWAY_ADMIN_PASSWORD
          value: password
        - name: EAM_SETUP_INSTALLSELECTION
          value: Controller
        ports:
        - name: ignition-http
          containerPort: 8088
        - name: ignition-https
          containerPort: 8043
        - name: port8060
          containerPort: 8060
        volumeMounts:
        - mountPath: /usr/local/bin/ignition/data
          name: scadafrontend-data
        readinessProbe:
          exec:
            command:
            - health-check.sh
            - -t
            - "3"
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
          timeoutSeconds: 3
      volumes:
      - name: scadafrontend-data
        persistentVolumeClaim:
          claimName: scadafrontend-data
