apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: servarr
  namespace: media
spec:
  generators:
  - git:
      repoURL: https://github.com/tannerru/K3s_Manifests.git
      revision: HEAD
      directory:
        recurse: true
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/tannerru/K3s_Manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=false