apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media
  labels:
    dep: prowlarr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
     
      
      
    spec:
      containers:
        - name: prowlarr
          
          image: linuxserver/prowlarr:nightly
          resources:
            requests: 
              memory: 500m
              cpu: 500m
            limits:
              memory: 4Gi
              
          ports:
            - containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: /config  

      volumes:
        - name: config
          persistentVolumeClaim:
             claimName: prowlarr-config
