apiVersion: v1
kind: Service
metadata:
  name: prowlarr-service
  
  namespace: media
  labels:
    app: prowlarr_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9696
    
  selector:    
    app: prowlarr
  type: LoadBalancer
  loadBalancerIP: 10.0.40.169