apiVersion: v1
kind: Service
metadata:
  name: transmission-service
  
  namespace: media
  labels:
    app: transmission_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
    
  selector:    
    app: transmission
  type: LoadBalancer
  loadBalancerIP: 10.0.40.170