apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    dep: sonarr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: sonarr
          image: linuxserver/sonarr:3.0.9
          resources:
            requests: 
              memory: 500m
              cpu: 500m
            limits:
              memory: 4Gi
          env:
          - name: PUID
            value: "0"
          - name: PGID
            value: "0"
          - name: UMASK
            value: "000"
             
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: media
              mountPath: /media

            - name: config
              mountPath: /config


      volumes:
        - name: media
          nfs:
            server: 10.0.50.4
            path: /mnt/Slow/Media
            nfsvers: "4.1"
            
        - name: config
          persistentVolumeClaim:
             claimName: sonarr-config
