apiVersion: v1
kind: Service
metadata:
  name: sonarr-service
  
  namespace: media
  labels:
    app: sonarr_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8989
    protocol: TCP
    targetPort: 8989
    
  selector:    
    app: sonarr
  type: LoadBalancer
  loadBalancerIP: 10.0.40.161