apiVersion: v1
kind: Service
metadata:
  name: calibre-web-service
  
  namespace: media
  labels:
    app: calibre-web_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8083
    protocol: TCP
    targetPort: 8083

   
  selector:    
    app: calibre-web
  type: LoadBalancer
  loadBalancerIP: 10.0.40.172