apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scadabackend-data
  namespace: scada
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi