apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  namespace: media
  labels:
    dep: readarr-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      labels:
        app: readarr
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: readarr
          
          image: linuxserver/readarr
          resources:
            requests: 
              memory: 500m
              cpu: 500m
            limits:
              memory: 8Gi
             
          ports:
          - name: port8787
            containerPort: 8787
        
        
          volumeMounts:
            - name: books
              mountPath: /books
            - name: config
              mountPath: /config

       volumes:
        - name: books
          nfs:
            server: 10.0.50.4
            path: /mnt/Slow/Media/books

        - name: config
          persistentVolumeClaim:
             claimName: readarr-config
