apiVersion: v1
kind: Service
metadata:
  name: readarr-service
  
  namespace: media
  labels:
    app: readarr_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8787
  
  selector:    
    app: readarr
  type: LoadBalancer
  loadBalancerIP: 10.0.40.173