apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
  namespace: media
  labels:
    dep: sabnzbd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-conf
      
    spec:
      containers:
        - name: sabnzbd
          
          image: binhex/arch-sabnzbd
          resources:
            requests: 
              memory: 500m
              cpu: 500m
            limits:
              memory: 8Gi
             
          ports:
          - name: port8080
            containerPort: 8080
          - name: port8090
            containerPort: 8090
        
          volumeMounts:
            - name: media
              mountPath: media/Downloads

            - name: config
              mountPath: /config

      volumes:
        - name: media
          nfs:
            server: 10.0.50.4
            path: /mnt/Slow/Media

        - name: config
          persistentVolumeClaim:
             claimName: sabnzbd-config
