apiVersion: v1
kind: Service
metadata:
  name: sabnzbd-service
  
  namespace: media
  labels:
    app: sabnzbd_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: http2
    port: 8090
    protocol: TCP
    targetPort: 8090
   
  selector:    
    app: sabnzbd
  type: LoadBalancer
  loadBalancerIP: 10.0.40.165