apiVersion: apps/v1
kind: Deployment
metadata:
  name: scada-backend
  namespace: scada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scada-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: scada-backend
    spec:
      initContainers:
      - name: seed-volume
        image: inductiveautomation/ignition:8.1.17
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        command:
        - sh
        - -c
        - >
          if [ ! -f /data/.ignition-seed-complete ]; then
            touch /data/.ignition-seed-complete ;
            cp -dpR /usr/local/bin/ignition/data/* /data/ ;
          fi
        volumeMounts:
        - mountPath: /data
          name: scadabackend-data
      containers:
      - name: scada-backend
        image: inductiveautomation/ignition:8.1.17
        resources:
          limits:
            memory: "4096Mi"
            cpu: "1000m"
        env:
        - name: ACCEPT_IGNITION_EULA
          value: "Y"
        - name: TZ
          value: “America/Chicago”
        - name: IGNITION_EDITION
          value: standard
        - name: GATEWAY_ADMIN_PASSWORD
          value: password
        ports:
        - name: ignition-http
          containerPort: 8088
        - name: ignition-https
          containerPort: 8043
        volumeMounts:
        - mountPath: /usr/local/bin/ignition/data
          name: scadabackend-data
        readinessProbe:
          exec:
            command:
            - n ignition-backend
            - m 2096
            - health-check.sh
            - -t
            - "3"
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 10
          timeoutSeconds: 3
      volumes:
      - name: scadabackend-data
        persistentVolumeClaim:
         claimName: scadabackend-data