apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scadabackend-data
  namespace: scada
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
