apiVersion: v1
kind: Service
metadata:
  name: radarr-service
  
  namespace: media
  labels:
    app: radarr_service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 7878
    
  selector:    
    app: radarr
  type: LoadBalancer
  loadBalancerIP: 10.0.40.162